"""
Django settings for werecat project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages
import dj_database_url
if os.path.isfile('env.py'):
    import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')

# Cloudinary imports

import cloudinary
import cloudinary.uploader
import cloudinary.api

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = False

# Define allowed hosts for the application

ALLOWED_HOSTS = ['8000-swewi-werecatblog-7tdy8qpovj1.ws-eu114.gitpod.io', '.herokuapp.com']

# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Custom admin interface - loaded here as per Jazzmin page requirements
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',  # Cloudinary storage for media files
    'django.contrib.sites',
    'allauth',  # Authentication apps
    'allauth.account',
    'allauth.socialaccount',
    'crispy_forms',  # Forms styling
    'crispy_bootstrap5',
    'django_summernote',  # Text editor for admin
    'cloudinary',  # Cloudinary for image uploads
    'blog',  # Blog app
    'about',  # About page app
    'contact',  # Contact form app
    'gallery',  # Gallery app
]

# Set the ID for the current site (used by 'django.contrib.sites')

SITE_ID = 1

# URL to redirect to after login

LOGIN_REDIRECT_URL = '/'

# URL to redirect to after logout

LOGOUT_REDIRECT_URL = '/'

# Configure Crispy Forms to use Bootstrap 5

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Middleware configuration

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Root URL configuration

ROOT_URLCONF = 'werecat.urls'

# Templates configuration

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI application

WSGI_APPLICATION = 'werecat.wsgi.application'

# Database configuration using dj_database_url for environment variable parsing

"""
Retained this information so I can use this data-base after assesment for CV.

https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""

DATABASES = {
    'default': dj_database_url.parse(os.environ.get("DATABASE_URL"))
}

# Trusted origins for CSRF protection

CSRF_TRUSTED_ORIGINS = [
    "https://8000-swewi-werecatblog-7tdy8qpovj1.ws-eu114.gitpod.io",
    "https://*.herokuapp.com"
]

# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Email verification setting for user accounts

ACCOUNT_EMAIL_VERIFICATION = 'none'

# Internationalization settings

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images) settings

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cloudinary configuration for media storage

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get("CLOUDINARY_CLOUD_NAME"),
    'API_KEY': os.environ.get("CLOUDINARY_API_KEY"),
    'API_SECRET': os.environ.get("CLOUDINARY_API_SECRET"),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Jazzmin Settings for customizing the admin interface

JAZZMIN_SETTINGS = {
    "site_title": "Werecat Blog",
    "site_header": "Werecat",
    "site_brand": "Werecat Industries",
    "site_icon": "images/favicon.png",
    "site_logo": None,
    "welcome_sign": "Welcome to the Werecat Blog",
    "copyright": "Werecat Blog",
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Werecat Blog", "url": "home", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["auth", "blog", "posts", "comments", "users.User"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "users.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "admin.LogEntry": "fas fa-file",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-arrow-circle-right",
    "related_modal_active": False,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    "hide_apps": ["django_summernote", "sites", "socialaccount"],
}

# Jazzmin UI tweaks

JAZZMIN_UI_TWEAKS = {
    "theme": "cyborg",
}