# Generated by Django 4.2.13 on 2024-05-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_image_gallery_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
